### PR TITLE
Tagging of authors rather than just displaying their name

### PR DESCRIPTION
**Pull request by d-korni**

### CODE REVIEW

**Comment by climu** [comment]
Do we really want to tag users while listing them? If fear users will end up being taged quite often for no reason expect someone curious about who as a role.

**Comment by d-korni** [comment]
It won't tag the users, but the authors. Because we delete the original message, as the authors name was I  the command, people could not click on the name of the person issuing the command. All this does is to make a mention of the author (self who issued the command), so there will be no disruption.

**Comment by climu** [comment]
right silly me!

**Comment by d-korni** [comment]
I think it would be too much even for me to tag all the users each time somebody wants to play with !whos_LFG ^^

**Pull request merged**
